### ISSUE TITLE
README.md wikipedia_en_all_novid_2018-10.zim (79GB, all English articles, no pictures/videos)

### ISSUE THREAD

**Issue by raszpl** [pirate/wikipedia-mirror#1]
> wikipedia_en_all_novid_2018-10.zim (79GB, all English articles, no pictures/videos)

should read
`wikipedia_en_all_novid_2018-10.zim (79GB, all English articles and pictures, no videos)`
or alternatively
`wikipedia_en_all_nopic_2018-09.zim (37GB, all English articles, no pictures/videos)
`

**Comment by pirate** [comment]
afaik it does not contain pictures, if it did it would be many hundreds of gigabytes I think.

**Comment by raszpl** [comment]
It does, the wikipedia_en_all_**nopic**_2018-09.zim one is supposed to be bare text
from wiki:
>All of English-language Wikipedia, with pictures, fits on a USB stick (54 GB as of May 2016, or 16 GB with no pictures)

**Comment by pirate** [comment]
I think the 2018 one being 79GB with no pic or video probably fits the growth curve from 2016, I highly doubt all the inline images for 6 million wikipedia articles somehow manage to fit in a 79GB archive.  If we can get confirmation from someone who has actually extracted/inspected the ZIM archives that would be helpful, my server that's holding it is down right now and I don't have a lot of time in the next two weeks to play around with this unfortunately.

**Comment by raszpl** [comment]
ZIM files do not contain 1:1 copy of wikipedia media library. They are re compressed with reduced quality.

**Comment by pirate** [comment]
```
[   ] wikipedia_en_all_mini_2019-09.zim             2019-09-18 03:16   10G   
[   ] wikipedia_en_all_nopic_2018-09.zim            2018-09-26 16:43   35G   
[   ] wikipedia_en_all_novid_2018-06.zim            2018-07-18 21:21   77G   
[   ] wikipedia_en_all_novid_2018-10.zim            2018-11-06 12:43   78G 
```
Considering these are the options I guess you're right, I'm amazed at how small they managed to get 6 million articles worth of images and video!

**Comment by pirate** [comment]
fixed
