### ISSUE TITLE
Few remarks about the README

### ISSUE THREAD

**Issue by kelson42** [pirate/wikipedia-mirror#3]
The README.md is a good explanation work :)

Here my few comments:
* We have permalinks for releases which could advantageously replace https://mirrors.dotsrc.org/kiwix/release/kiwix-tools/kiwix-tools_linux-x86_64-3.0.1.tar.gz by https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz
* I would recommend AFAP to recommend HTTPS over HTTP, so better https://download.kiwix.org/zim/wikipedia_en_all_novid.zim over https://download.kiwix.org/zim/wikipedia_en_all_novid.zim
* `novid` links will be soon be replaced by `maxi`, it is just a naming convention, so https://download.kiwix.org/zim/wikipedia_en_all_maxi.zim
* ZIM/Kiwix *has* fulltext to the contrary to what you have written.
* Wikipedia categories will come soon, this is still in alpha.
* About the list of ZIMs, Wikipedia list is a mirror of https://download.kiwix.org/zim/wikipedia/
* All the links on download.kiwix.org have a BitTorrent file, just add `.torrent` to any URL
* The publication is not regularly like you have noticed, but our goal is one time a month for most of them. Still working on it (We are searching for HW to support us).
* I would recommend to use permalinks everywhere, to avoid having to update the READMEmd

**Comment by pirate** [comment]
> * [X] We have permalinks for releases which could advantageously replace https://mirrors.dotsrc.org/kiwix/release/kiwix-tools/kiwix-tools_linux-x86_64-3.0.1.tar.gz by https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz
> * [X] I would recommend ASAP to recommend HTTPS over HTTP, so better https://download.kiwix.org/zim/wikipedia_en_all_novid.zim over https://download.kiwix.org/zim/wikipedia_en_all_novid.zim
> * [X] `novid` links will be soon be replaced by `maxi`, it is just a naming convention, so https://download.kiwix.org/zim/wikipedia_en_all_maxi.zim
> * [X] ZIM/Kiwix *has* fulltext to the contrary to what you have written.
> * [X] Wikipedia categories will come soon, this is still in alpha.
> * [X] About the list of ZIMs, Wikipedia list is a mirror of https://download.kiwix.org/zim/wikipedia/
> * [X] All the links on download.kiwix.org have a BitTorrent file, just add `.torrent` to any URL
> * The publication is not regularly like you have noticed, but our goal is one time a month for most of them. Still working on it (We are searching for HW to support us).
> * I would recommend to use permalinks everywhere, to avoid having to update the READMEmd

Finally got around to making most of these changes: https://github.com/pirate/wikipedia-mirror/commit/8cf535d9a496c3377e5626a46a206018a3921011

Let me know if you see anything else that should be changed, thanks!

**Comment by pirate** [comment]
@kelson42 how much hardware do you need BTW? I have a server with a gigabit connection, 24 cores, and ~10TB sitting mostly unused. I could give you a pretty big VM on it if you needed.

**Comment by kelson42** [comment]
@pirate Thank you for the offer. This would be really useful. Our ZIMfarm is meanwhile pretty open and we have instructions to setup a worker in a few minutes https://farm.openzim.org/about. Let me know if this would be doable and we could discuss the last few details on Slack.
