### ISSUE TITLE
Is there a way to keep the local dump up to date?

### ISSUE THREAD

**Issue by balki** [pirate/wikipedia-mirror#4]
Thank you for the guide. It would be helpful to include a way to keep the setup up to date periodically. I wish there was a way to to just download the 'diff' every month instead of complete dump.

**Comment by pirate** [comment]
I think unfortunately this is something that would have to be provided by Kiwix or the content creators themselves and is out of my control, I don't know of any download sources for only the diffs off the top of my head.  If you find something feel free to post back here and I'll reopen this!

**Comment by kelson42** [comment]
@balki Incremental update has always be a topic at Kiwix. Unfortunately we are not ready yet for that. We are even not sure about the technology stack to provide this feature. We have work to do around Mirrorbrain to get it work properly with zsync... we would then check if zsync would be a good candidate. See https://github.com/kiwix/maintenance/issues/37
