### ISSUE TITLE
Can't load .env variables into .conf

### ISSUE THREAD

**Issue by jwise-mfg** [pirate/wikipedia-mirror#5]
This line generates the .conf from the template, but doesn't seem to load any of the sourced .env variables -- nginx -t reports them as invalid...

```
# Fill your config options into nginx.conf.template to create nginx.conf
envsubst \
    "$(printf '${%s} ' $(bash -c "compgen -A variable"))"\
    < "$CONFIG_DIR/nginx.conf.template" \
    > "$CONFIG_DIR/nginx.conf"
```

**Comment by pirate** [comment]
I'd just do it by hand, there arent too many variables it actually uses in the template, and this was just a convenience suggestion I provided to autofill them (didn't test it myself).

**Comment by jwise-mfg** [comment]
I am trying that, through trial and error, but an example of what it should look like would help a lot. I've successfully added a few like this at the top of the .conf file:
`env PROJECT_DIR=/opt/wiki;`
Where the variable value is an uninterrupted string. But variables like this throw errors:
`env CACHE_REQUESTS=GET HEAD POST;`
Error is:
```
nginx: [emerg] invalid number of arguments in "env" directive in /etc/nginx/nginx.conf:23
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by jwise-mfg** [comment]
If leave out the troublesome variables, I get further validation errors like:
```
invalid max_size value "max_size=$CACHE_SIZE" in /etc/nginx/nginx.conf:114
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Where my env line looks like: `env CACHE_SIZE=1GB;`

**Comment by pirate** [comment]
I recommend following nginx docs to resolve any individual issues with nginx config keys: https://www.nginx.com/blog/nginx-caching-guide/

As mentioned in those docs, the format for that config key is `max_size=10g` not `max_size=10GB`.
